In [1]:
from pathlib import Path
import json
import pandas as pd


BASE_DIR = Path("main.ipynb").resolve().parents[1]
DATA_DIR = BASE_DIR / "data" / "processed"

JSON_PATH = DATA_DIR / "survey_v1.1.json" # survey1 not survey

df = pd.read_json(JSON_PATH)

In [2]:
df.head()

,id,MEAS_REF,MEAS_REN,MEAS_NEW,MEAS_NO,REN_1,REN_2,REN_3,REN_4,REN_5,...,HOUSE_Size5,HOUSE_Size6,HOUSE_Size7,HOUSE_Size8,HOUSE_Income,REF_Thermische_Sanierung,REF_Heizungstausch,GROUP_BEH,Gemeindenummer,Gemeindename
0,1,1,1,0,0,0.0,1.0,1.0,0.0,0.0,...,0,1,1,0,4.0,1,1,1.0,61263,Rottenmann
1,2,0,0,1,0,NaN,NaN,NaN,NaN,NaN,...,2,0,0,0,5.0,0,0,5.0,62233,Pinggau
2,3,0,1,0,0,1.0,1.0,0.0,0.0,0.0,...,0,1,0,0,3.0,0,0,NaN,61255,Bad Mitterndorf
3,4,1,0,0,0,NaN,NaN,NaN,NaN,NaN,...,0,0,2,0,3.0,1,1,1.0,60350,Stainz
4,5,1,1,0,0,1.0,1.0,0.0,1.0,1.0,...,0,2,0,0,4.0,1,1,1.0,61757,Birkfeld

In [3]:
df.tail()

,id,MEAS_REF,MEAS_REN,MEAS_NEW,MEAS_NO,REN_1,REN_2,REN_3,REN_4,REN_5,...,HOUSE_Size5,HOUSE_Size6,HOUSE_Size7,HOUSE_Size8,HOUSE_Income,REF_Thermische_Sanierung,REF_Heizungstausch,GROUP_BEH,Gemeindenummer,Gemeindename
1646,1647,1,1,0,0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,2.0,0,1,2.0,62379,Feldbach
1647,1648,1,1,0,0,1.0,1.0,1.0,0.0,0.0,...,0,2,0,0,3.0,1,0,3.0,61265,Schladming
1648,1649,1,1,1,0,0.0,0.0,0.0,1.0,0.0,...,0,1,1,0,6.0,1,0,NaN,61444,Scheifling
1649,1650,0,0,0,1,NaN,NaN,NaN,NaN,NaN,...,0,0,0,2,4.0,0,0,6.0,61108,Leoben
1650,1651,0,0,0,1,NaN,NaN,NaN,NaN,NaN,...,0,1,1,0,3.0,0,0,6.0,61750,Strallegg

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1651 entries, 0 to 1650
Columns: 143 entries, id to Gemeindename
dtypes: float64(117), int64(16), object(10)
memory usage: 1.8+ MB

In [5]:
df.describe()

,id,MEAS_REF,MEAS_REN,MEAS_NEW,MEAS_NO,REN_1,REN_2,REN_3,REN_4,REN_5,...,SOCIO_Country1,HOUSE_Education,HOUSE_Size1,HOUSE_Size2,HOUSE_Size3,HOUSE_Income,REF_Thermische_Sanierung,REF_Heizungstausch,GROUP_BEH,Gemeindenummer
count,1651.000000,1651.000000,1651.000000,1651.000000,1651.000000,836.000000,836.000000,836.000000,836.000000,836.000000,...,1644.000000,1645.000000,1641.000000,1651.000000,1651.000000,1563.000000,1651.000000,1651.000000,1459.000000,1651.000000
mean,826.000000,0.725621,0.506360,0.173834,0.105391,0.586124,0.723684,0.221292,0.255981,0.309809,...,1.074209,3.094225,0.203534,0.308904,0.114476,3.349328,0.502726,0.543307,2.714873,61355.621442
std,476.746963,0.446336,0.500111,0.379082,0.307149,0.492822,0.447443,0.415365,0.436672,0.462691,...,0.472588,0.850216,0.554373,0.666269,0.402540,1.199996,0.500144,0.498272,1.824875,776.359956
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,60101.000000
25%,413.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,2.000000,0.000000,0.000000,0.000000,2.500000,0.000000,0.000000,1.000000,60654.000000
50%,826.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,...,1.000000,3.000000,0.000000,0.000000,0.000000,3.000000,1.000000,1.000000,2.000000,61413.000000
75%,1238.500000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,...,1.000000,4.000000,0.000000,0.000000,0.000000,4.000000,1.000000,1.000000,4.000000,62139.000000
max,1651.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,7.000000,5.000000,5.000000,6.000000,4.000000,7.000000,1.000000,1.000000,6.000000,62390.000000

### Show all columns

In [6]:
pd.set_option('display.max_columns', None)
df

,id,MEAS_REF,MEAS_REN,MEAS_NEW,MEAS_NO,REN_1,REN_2,REN_3,REN_4,REN_5,REN_6,REN_7,REN_Year,REF_1,REF_2,REF_3,REF_4,REF_5,REF_6,REF_7,REF_8,REF_9,REF_10,REF_11,REF_Year,NEW_Type,NEW_ES_Con0,NEW_ES_Con1,NEW_ES_Con2,NEW_ES_Con3,NEW_ES_Con4,NEW_ES_Con5,NEW_HS_Con0,NEW_HS_Con1,NEW_HS_Con2,NEW_HS_Con3,NEW_HS_Con4,NEW_HS_Con5,NEW_HS_Con6,NEW_HS_Con7,NEW_HS_Con8,NEW_HS_Con9,NEW_HP_Con0,NEW_HP_Con1,NEW_HP_Con2,NEW_HP_Con3,NEW_HP_Con4,NEW_HP_Con5,NEW_Year,TRIG_1Text,TRIG_2Text,TRIG_1,TRIG_2,TRIG_3,TRIG_4,SUB,SUB_1,SUB_2,SUB_3,SUB_5,SUB_4,INFO_S1,INFO_S2,INFO_S3,INFO_S4,INFO_S5,INFO_S6,INFO_S7,INFO_S8,INFO_S9,INFO_S10,INFO_S11,INFO_S12,INFO_C1,INFO_C2,INFO_C3,INFO_C4,INFO_C5,INFO_C6,INFO_C7,INFO_C8,INFO_C9,INFO_PAS,INFO_ACT,CHAR_B1,CHAR_B2,CHAR_B3,CHAR_B4,CHAR_HS1,CHAR_HS2,CHAR_HS3,CHAR_HS4,CHAR_HS5,CHAR_HS6,CHAR_HS7,BUILD_Type,BUILD_Size,BUILD_Use,BUILD_Use_Year,BUILD_Residence,BUILD_Age,BUILD_ES_Cur,BUILD_ES_Old,BUILD_HS1,BUILD_HS2,BUILD_HS3,BUILD_HS4,BUILD_HS5,BUILD_HS6,BUILD_HS7,BUILD_HS8,BUILD_HS9,BUILD_HS10,BUILD_HP,BUILD_HS1_Old,BUILD_HS2_Old,BUILD_HS3_Old,BUILD_HS4_Old,BUILD_HS5_Old,BUILD_HS6_Old,BUILD_HS7_Old,BUILD_HS8_Old,BUILD_HS9_Old,BUILD_HS10_Old,BUILD_HS_Age,SOCIO_Gender1,SOCIO_Age1,SOCIO_Country1,HOUSE_Education,HOUSE_Size1,HOUSE_Size2,HOUSE_Size3,HOUSE_Size4,HOUSE_Size5,HOUSE_Size6,HOUSE_Size7,HOUSE_Size8,HOUSE_Income,REF_Thermische_Sanierung,REF_Heizungstausch,GROUP_BEH,Gemeindenummer,Gemeindename
0,1,1,1,0,0,0.0,1.0,1.0,0.0,0.0,1.0,NaN,2022.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,NaN,2013.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"Hoher Energieverbrauch, Kälte von unten",Auszug der Mutter ins Altersheim,3.0,1.0,1.0,4.0,1.0,NaN,1.0,1.0,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,1.0,1.0,NaN,NaN,3.0,3.0,3,2.0,3,1,2.0,4.0,3.0,1.0,3.0,5.0,2.0,1,2.0,1,46.0,1.0,5,6.0,6.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2014,1.0,1966.0,5.0,4.0,0.0,0,0,0,0,1,1,0,4.0,1,1,1.0,61263,Rottenmann
1,2,0,0,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2018,Familiengründung - Geburt von Kindern,Umzug von Wien in die Oststeiermark,2.0,2.0,NaN,2.0,1.0,NaN,1.0,NaN,NaN,NaN,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,3.0,NaN,3,2.0,3,1,2.0,3.0,2.0,2.0,2.0,2.0,2.0,1,1.0,1,5.0,1.0,8,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018,2.0,1984.0,1.0,4.0,2.0,0,0,0,2,0,0,0,5.0,0,0,5.0,62233,Pinggau
2,3,0,1,0,0,1.0,1.0,0.0,0.0,0.0,1.0,NaN,2010.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,2.0,3.0,2.0,4.0,1.0,1.0,1.0,1.0,NaN,NaN,3.0,1.0,3.0,3.0,0.0,0.0,0.0,0.0,2.0,0.0,3.0,NaN,NaN,1.0,1.0,1.0,1.0,NaN,1.0,NaN,NaN,3.0,3.0,3,1.0,3,1,1.0,4.0,4.0,1.0,1.0,1.0,2.0,1,2.0,1,9.0,1.0,5,4.0,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020,2.0,1977.0,1.0,3.0,0.0,1,0,0,0,1,0,0,3.0,0,0,NaN,61255,Bad Mitterndorf
3,4,1,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,2018.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,Haus war renovierungsbedürftig,Alte Fassade aus Eternit,1.0,2.0,3.0,2.0,1.0,1.0,1.0,1.0,NaN,NaN,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,3.0,3,2.0,2,2,3.0,2.0,3.0,1.0,1.0,3.0,5.0,1,1.0,0,NaN,1.0,4,3.0,5.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021,2.0,1959.0,1.0,3.0,0.0,0,0,0,0,0,2,0,3.0,1,1,1.0,60350,Stainz
4,5,1,1,0,0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,2010.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,NaN,2010.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,Hauskauf,None,1.0,1.0,1.0,4.0,1.0,1.0,1.0,1.0,NaN,NaN,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,NaN,NaN,1.0,NaN,NaN,1.0,NaN,1.0,NaN,NaN,1.0,3.0,4,1.0,4,1,1.0,4.0,4.0,1.0,1.0,1.0,1.0,1,1.0,1,4.0,1.0,6,2.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020,2.0,1971.0,1.0,4.0,0.0,0,2,0,0,2,0,0,4.0,1,1,1.0,61757,Birkfeld
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1646,1647,1,1,0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,2020.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,Energie Kosten,Autark sein,1.0,1.0,2.0,4.0,0.0,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,2.0,2,2.0,2,1,2.0,4.0,4.0,4.0,1.0,1.0,2.0,2,3.0,1,30.0,1.0,5,4.0,5.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015,2.0,1994.0,1.0,3.0,5.0,0,0,0,0,0,0,0,2.0,0,1,2.0,62379,Feldbach
1647,1648,1,1,0,0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,2022.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,NaN,2016.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,Heizkosten,Stromkosten,1.0,1.0,2.0,3.0,1.0,1.0,1.0,1.0,NaN,NaN,2.0,2.0,2.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,NaN,1.0,1.0,NaN,NaN,1.0,NaN,1.0,NaN,NaN,2.0,3.0,3,2.0,2,2,3.0,2.0,3.0,2.0,3.0,3.0,2.0,2,3.0,1,42.0,1.0,6,4.0,6.0,NaN,NaN,NaN,1.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017,2.0,1969.0,1.0,4.0,0.0,0,0,0,0,2,0,0,3.0,1,0,3.0,61265,Schladming
1648,1649,1,1,1,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2010.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,NaN,2010.0,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021,Wohnmöglichkeit für Tochter,Lärmschutz,2.0,2.0,2.0,2.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,2.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,NaN,1.0,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,3.0,1.0,2,2.0,2,2,3.0,2.0,2.0,2.0,2.0,3.0,2.0,2,2.0,1,26.0,1.0,1,6.0,6.0,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000,2.0,1948.0,2.0,4.0,0.0,0,0,2,0,1,1,0,6.0,1,0,NaN,61444,Scheifling
1649,1650,0,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,2,2,2.0,3.0,3.0,2.0,2.0,3.0,2.0,2,2.0,1,40.0,1.0,6,6.0,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012,1.0,1947.0,1.0,4.0,0.0,0,0,0,0,0,0,2,4.0,0,0,6.0,61108,Leoben
1650,1651,0,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,NaN,5,5,3.0,3.0,3.0,3.0,3.0,3.0,3.0,2,2.0,1,30.0,1.0,7,4.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012,2.0,1957.0,1.0,2.0,NaN,0,0,1,0,1,1,0,3.0,0,0,6.0,61750,Strallegg

### GROUP_BEH - clustering of households by the depth of change to green energy

In [11]:
df["SUB"].value_counts()

SUB
1.0    1185
0.0     277
2.0      14
Name: count, dtype: int64

### Classification Reference

| Code | Label | Meaning |
|------|-------|---------|
| 1 | HIGH | Transition Leader — Changed main heating system and did thermal renovation |
| 2 | MED_CO2 | CO2 Reducers — Changed main heating to renewable |
| 3 | MED_SAV | Energy Savers — Thermally insulated only |
| 4 | LOW | Technology Adopters — Only minor innovations (PV, battery, etc.) |
| 5 | NEW | New Builders — Built/rebuilt rather than retrofitted |
| 6 | NO | No Actions — Did nothing. |
| — | — | Cannot be assigned (the 192 missing) |

In [8]:
df["REF_Year"].value_counts()

REF_Year
2022.0    207
2021.0    155
2023.0    130
2020.0    122
2010.0    103
2019.0     93
2018.0     74
2017.0     49
2013.0     44
2016.0     39
2015.0     31
2014.0     30
2012.0     29
2011.0     16
Name: count, dtype: int64

In [9]:
# ref_year = df['REF_Year'].dropna().astype(int)
y2010 = df["REF_Year"][df["REF_Year"] <= 2010].count()

y10_23 = df["REF_Year"][df["REF_Year"] > 2010].count()

yna = df["REF_Year"][df["REF_Year"] != None].count()
print(y2010)
print(y10_23)
print(yna - y10_23 + y2010)

103
1019
206

In [10]:
y2010 = df["REN_Year"][df["REN_Year"] <= 2010].count()

y10_23 = df["REN_Year"][df["REN_Year"] > 2010].count()

yna = df["REN_Year"][df["REN_Year"] != None].count()
print(y2010)
print(y10_23)
print(yna - y10_23 + y2010)

80
644
160